name:  ci/cd pipeline to deploy to tomcat

on:
  push:
     branches:
       - master  # Runs pipeline onlu when pushing to master branch
jobs:
   build-deploy:
      runs-on: ubuntu-latest

      steps:
        # Checkout repo
        - name: Checkout code 
          uses: actions/checkout@v3

        # Set up java 
        - name: set up jdk 21
          uses: actions/setup-java@v3
          with: 
            distribution: 'temurin'
            java-version:  '21'
            
        # Build with  maven(update)
        - name: Build with maven
          run: mvn clean package
       # Build wuth sonarqube 
        - name: Cache SonarQube packages
          uses: actions/cache@v3
          with:
           path: ~/.sonar/cache
           key: ${{runner.os}}-sonar

        - name: Run SonarQube Scanner
          run: sonar:sonar http://${{secrets.SONAR_HOST_URL}}:9000 \
            - D sonar.login=${{secrets.SONAR_TOKEN}}
          
