name:  ci/cd pipeline to deploy to tomcat

on:
  push:
     branches:
       - master  # Runs pipeline onlu when pushing to master branch
jobs:
   build-deploy:
      runs-on: ubuntu-latest

      steps:
        # Checkout repo
        - name: Checkout code 
          uses: actions/checkout@v3

        # Set up java 
        - name: set up jdk 21
          uses: actions/setup-java@v3
          with: 
            distribution: 'temurin'
            java-version:  '21'
            
        #Build with  maven(update)
        - name: Build with maven
          run: mvn clean package
          
        #Deploy WAR to Tomcat  
        - name: Deploy to tomcat
          run: |
           - name: Deploy WAR to Tomcat
             run: |
               curl -v -u ${{secrets.TOMCAT_USER}}:${{secrets.TOMCAT_PASSWORD}} \
                -T target/TrainBook-1.0.0-SNAPSHOT.war\
                "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/TrainBook&update=true"

        
   
