name: SonarQube Scan (Maven)

on:
  push:
    branches:
      - master
jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2-${{ hashFiles('**/pom.xml')}}
          restore-keys: |
            ${{runner.os}}-m2

      - name: Build with Maven and run SonarQube analysis
        run: | 
         mvn clean verify sonar:sonar \
         -Dsonar.host.url=http://13.214.211.24:9000 \
         -Dsonar.login=${{secrets.SONAR_TOKEN}} \
         -Dsonar.projectKey=train-ticket-reservation
      # deploy to tomcat
      - name: deploy to tomcat
        run: |
          curl -u -v ${{secrets.TOMCAT_USER}}:${{secrets.TOMCAT_PASSWORD}}\
          -Ttarget/TrainBook-1.0.0-SANPSHOT.war\
          "http://${{secrets.TOMCAT_HOST}}:8080/manager/text/deploy?path=/TrainBook&update=true"


         
